name: Fetch and Update Analytics Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight UTC

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-analytics-data
        pip install pandas

    - name: Run fetch analytics data script
      run: python fetch_analytics_data.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: List files for debugging
      run: ls -la

    - name: Check contents of CSV file
      run: cat analytics_data.csv

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add analytics_data.csv
        git commit -m 'Updated analytics data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
