name: Fetch and Update Analytics Data

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests google-analytics-data pandas

    - name: Run fetch analytics data script
      run: python fetch_analytics_data.py
      env:
        KEY_FILE_CONTENT: ${{ secrets.KEY_FILE_CONTENT }}
        PROPERTY_ID: '446474801'

    - name: List files for debugging
      run: ls -la

    - name: Check contents of CSV file
      run: cat analytics_data.csv

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add analytics_data.csv
        git commit -m 'Updated analytics data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
